// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLightning.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NLightning.Infrastructure.Persistence.Postgres.Migrations
{
    [DbContext(typeof(NLightningDbContext))]
    [Migration("20251106194247_AddFieldsForChannelOpen")]
    partial class AddFieldsForChannelOpen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.BlockchainStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_at");

                    b.Property<byte[]>("LastProcessedBlockHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("last_processed_block_hash");

                    b.Property<long>("LastProcessedHeight")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processed_height");

                    b.HasKey("Id")
                        .HasName("pk_blockchain_states");

                    b.ToTable("blockchain_states", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.UtxoEntity", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_id");

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<long>("AddressIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("address_index");

                    b.Property<byte>("AddressType")
                        .HasColumnType("smallint")
                        .HasColumnName("address_type");

                    b.Property<long>("AmountSats")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_sats");

                    b.Property<long>("BlockHeight")
                        .HasColumnType("bigint")
                        .HasColumnName("block_height");

                    b.Property<bool>("IsAddressChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_address_change");

                    b.Property<byte[]>("LockedToChannelId")
                        .HasColumnType("bytea")
                        .HasColumnName("locked_to_channel_id");

                    b.Property<byte[]>("UsedInTransactionId")
                        .HasColumnType("bytea")
                        .HasColumnName("used_in_transaction_id");

                    b.HasKey("TransactionId", "Index")
                        .HasName("pk_utxos");

                    b.HasIndex("AddressType")
                        .HasDatabaseName("ix_utxos_address_type")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("LockedToChannelId")
                        .HasDatabaseName("ix_utxos_locked_to_channel_id")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("UsedInTransactionId")
                        .HasDatabaseName("ix_utxos_used_in_transaction_id")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("AddressIndex", "IsAddressChange", "AddressType")
                        .HasDatabaseName("ix_utxos_address_index_is_address_change_address_type")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("utxos", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletAddressEntity", b =>
                {
                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<bool>("IsChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_change");

                    b.Property<byte>("AddressType")
                        .HasColumnType("smallint")
                        .HasColumnName("address_type");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.HasKey("Index", "IsChange", "AddressType")
                        .HasName("pk_wallet_addresses");

                    b.ToTable("wallet_addresses", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WatchedTransactionEntity", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("bytea")
                        .HasColumnName("transaction_id");

                    b.Property<byte[]>("ChannelId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FirstSeenAtHeight")
                        .HasColumnType("bigint")
                        .HasColumnName("first_seen_at_height");

                    b.Property<long>("RequiredDepth")
                        .HasColumnType("bigint")
                        .HasColumnName("required_depth");

                    b.Property<int?>("TransactionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_index");

                    b.HasKey("TransactionId")
                        .HasName("pk_watched_transactions");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_watched_transactions_channel_id");

                    b.ToTable("watched_transactions", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelConfigEntity", b =>
                {
                    b.Property<byte[]>("ChannelId")
                        .HasColumnType("bytea")
                        .HasColumnName("channel_id");

                    b.Property<long?>("ChannelReserveAmountSats")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_reserve_amount_sats");

                    b.Property<long>("FeeRatePerKwSatoshis")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_rate_per_kw_satoshis");

                    b.Property<decimal>("HtlcMinimumMsat")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("htlc_minimum_msat");

                    b.Property<long>("LocalDustLimitAmountSats")
                        .HasColumnType("bigint")
                        .HasColumnName("local_dust_limit_amount_sats");

                    b.Property<byte[]>("LocalUpfrontShutdownScript")
                        .HasColumnType("bytea")
                        .HasColumnName("local_upfront_shutdown_script");

                    b.Property<int>("MaxAcceptedHtlcs")
                        .HasColumnType("integer")
                        .HasColumnName("max_accepted_htlcs");

                    b.Property<decimal>("MaxHtlcAmountInFlight")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("max_htlc_amount_in_flight");

                    b.Property<long>("MinimumDepth")
                        .HasColumnType("bigint")
                        .HasColumnName("minimum_depth");

                    b.Property<bool>("OptionAnchorOutputs")
                        .HasColumnType("boolean")
                        .HasColumnName("option_anchor_outputs");

                    b.Property<long>("RemoteDustLimitAmountSats")
                        .HasColumnType("bigint")
                        .HasColumnName("remote_dust_limit_amount_sats");

                    b.Property<byte[]>("RemoteUpfrontShutdownScript")
                        .HasColumnType("bytea")
                        .HasColumnName("remote_upfront_shutdown_script");

                    b.Property<int>("ToSelfDelay")
                        .HasColumnType("integer")
                        .HasColumnName("to_self_delay");

                    b.Property<byte>("UseScidAlias")
                        .HasColumnType("smallint")
                        .HasColumnName("use_scid_alias");

                    b.HasKey("ChannelId")
                        .HasName("pk_channel_configs");

                    b.ToTable("channel_configs", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", b =>
                {
                    b.Property<byte[]>("ChannelId")
                        .HasColumnType("bytea")
                        .HasColumnName("channel_id");

                    b.Property<byte?>("ChangeAddressAddressType")
                        .HasColumnType("smallint")
                        .HasColumnName("change_address_address_type");

                    b.Property<long?>("ChangeAddressIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("change_address_index");

                    b.Property<bool?>("ChangeAddressIsChange")
                        .HasColumnType("boolean")
                        .HasColumnName("change_address_is_change");

                    b.Property<byte?>("ChangeAddressType")
                        .HasColumnType("smallint")
                        .HasColumnName("change_address_type");

                    b.Property<long>("FundingAmountSatoshis")
                        .HasColumnType("bigint")
                        .HasColumnName("funding_amount_satoshis");

                    b.Property<long>("FundingCreatedAtBlockHeight")
                        .HasColumnType("bigint")
                        .HasColumnName("funding_created_at_block_height");

                    b.Property<int>("FundingOutputIndex")
                        .HasColumnType("integer")
                        .HasColumnName("funding_output_index");

                    b.Property<byte[]>("FundingTxId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("funding_tx_id");

                    b.Property<bool>("IsInitiator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initiator");

                    b.Property<byte[]>("LastReceivedSignature")
                        .HasColumnType("bytea")
                        .HasColumnName("last_received_signature");

                    b.Property<byte[]>("LastSentSignature")
                        .HasColumnType("bytea")
                        .HasColumnName("last_sent_signature");

                    b.Property<decimal>("LocalBalanceSatoshis")
                        .HasColumnType("numeric")
                        .HasColumnName("local_balance_satoshis");

                    b.Property<decimal>("LocalNextHtlcId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("local_next_htlc_id");

                    b.Property<decimal>("LocalRevocationNumber")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("local_revocation_number");

                    b.Property<byte[]>("PeerEntityNodeId")
                        .HasColumnType("bytea")
                        .HasColumnName("peer_entity_node_id");

                    b.Property<decimal>("RemoteBalanceSatoshis")
                        .HasColumnType("numeric")
                        .HasColumnName("remote_balance_satoshis");

                    b.Property<decimal>("RemoteNextHtlcId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("remote_next_htlc_id");

                    b.Property<byte[]>("RemoteNodeId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("remote_node_id");

                    b.Property<decimal>("RemoteRevocationNumber")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("remote_revocation_number");

                    b.Property<byte>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<byte>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("ChannelId")
                        .HasName("pk_channels");

                    b.HasIndex("PeerEntityNodeId")
                        .HasDatabaseName("ix_channels_peer_entity_node_id");

                    b.HasIndex("ChangeAddressIndex", "ChangeAddressIsChange", "ChangeAddressAddressType")
                        .HasDatabaseName("ix_channels_change_address_index_change_address_is_change_chan");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelKeySetEntity", b =>
                {
                    b.Property<byte[]>("ChannelId")
                        .HasColumnType("bytea")
                        .HasColumnName("channel_id");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local");

                    b.Property<decimal>("CurrentPerCommitmentIndex")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("current_per_commitment_index");

                    b.Property<byte[]>("CurrentPerCommitmentPoint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("current_per_commitment_point");

                    b.Property<byte[]>("DelayedPaymentBasepoint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("delayed_payment_basepoint");

                    b.Property<byte[]>("FundingPubKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("funding_pub_key");

                    b.Property<byte[]>("HtlcBasepoint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("htlc_basepoint");

                    b.Property<long>("KeyIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("key_index");

                    b.Property<byte[]>("LastRevealedPerCommitmentSecret")
                        .HasColumnType("bytea")
                        .HasColumnName("last_revealed_per_commitment_secret");

                    b.Property<byte[]>("PaymentBasepoint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payment_basepoint");

                    b.Property<byte[]>("RevocationBasepoint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("revocation_basepoint");

                    b.HasKey("ChannelId", "IsLocal")
                        .HasName("pk_channel_key_sets");

                    b.ToTable("channel_key_sets", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.HtlcEntity", b =>
                {
                    b.Property<byte[]>("ChannelId")
                        .HasColumnType("bytea")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("HtlcId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("htlc_id");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<byte[]>("AddMessageBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("add_message_bytes");

                    b.Property<decimal>("AmountMsat")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("amount_msat");

                    b.Property<long>("CltvExpiry")
                        .HasColumnType("bigint")
                        .HasColumnName("cltv_expiry");

                    b.Property<decimal>("ObscuredCommitmentNumber")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("obscured_commitment_number");

                    b.Property<byte[]>("PaymentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payment_hash");

                    b.Property<byte[]>("PaymentPreimage")
                        .HasColumnType("bytea")
                        .HasColumnName("payment_preimage");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<byte>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.HasKey("ChannelId", "HtlcId", "Direction")
                        .HasName("pk_htlcs");

                    b.ToTable("htlcs", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Node.PeerEntity", b =>
                {
                    b.Property<byte[]>("NodeId")
                        .HasColumnType("bytea")
                        .HasColumnName("node_id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("Port")
                        .HasColumnType("bigint")
                        .HasColumnName("port");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("NodeId")
                        .HasName("pk_peers");

                    b.ToTable("peers", (string)null);
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.UtxoEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletAddressEntity", "WalletAddress")
                        .WithMany("Utxos")
                        .HasForeignKey("AddressIndex", "IsAddressChange", "AddressType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_utxos_wallet_addresses_address_index_is_address_change_addr");

                    b.Navigation("WalletAddress");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WatchedTransactionEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", null)
                        .WithMany("WatchedTransactions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watched_transactions_channels_channel_id");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelConfigEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", null)
                        .WithOne("Config")
                        .HasForeignKey("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelConfigEntity", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_configs_channels_channel_id");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Node.PeerEntity", null)
                        .WithMany("Channels")
                        .HasForeignKey("PeerEntityNodeId")
                        .HasConstraintName("fk_channels_peers_peer_entity_node_id");

                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletAddressEntity", "ChangeAddress")
                        .WithMany()
                        .HasForeignKey("ChangeAddressIndex", "ChangeAddressIsChange", "ChangeAddressAddressType")
                        .HasConstraintName("fk_channels_wallet_addresses_change_address_index_change_addre");

                    b.Navigation("ChangeAddress");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelKeySetEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", null)
                        .WithMany("KeySets")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_key_sets_channels_channel_id");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.HtlcEntity", b =>
                {
                    b.HasOne("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", null)
                        .WithMany("Htlcs")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_htlcs_channels_channel_id");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Bitcoin.WalletAddressEntity", b =>
                {
                    b.Navigation("Utxos");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Channel.ChannelEntity", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Htlcs");

                    b.Navigation("KeySets");

                    b.Navigation("WatchedTransactions");
                });

            modelBuilder.Entity("NLightning.Infrastructure.Persistence.Entities.Node.PeerEntity", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
