name: NLightning Combined Coverage Report (Push)
on:
  workflow_run:
    workflows: ["NLightning .NET Build & Tests (Push)", "NLightning.Native .NET Build & Tests (Push)", "NLightning.Wasm .NET Build & Tests (Push)"]
    types:
      - completed

jobs:
  combined-report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Download Standard Coverage
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dotnet.yml
          name: coverage
          path: coverage-reports/standard

      - name: Download Native Coverage
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dotnet.native.yml
          name: coverage.Native
          path: coverage-reports/native

      - name: Download WASM Coverage
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dotnet.wasm.yml
          name: coverage.Wasm
          path: coverage-reports/wasm

      - name: List All Downloaded Files
        run: find coverage-reports -type f | sort

      - name: Combine All Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: "coverage-reports/**/Cobertura.xml"
          targetdir: "${{ github.workspace }}/combined-report"
          reporttypes: "Cobertura;Html;Badges"
          verbosity: "Info"
          title: "Combined Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgeneratortool"
          assemblyfilters: "+*;-NLightning.Infrastructure.Blazor;-NLightning.BlazorTestApp"

      - name: Generate Combined Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: combined-report/Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '50 75'

      - name: Copy Reports to DocFX
        run: |
          mkdir -p .docfx/docs/coverage-reports
          cp -r combined-report/* .docfx/docs/coverage-reports/

      - name: Upload Coverage for DocFX
        uses: actions/upload-artifact@v4
        with:
          name: coverage-docfx
          path: .docfx/docs/coverage-reports/
          retention-days: 5