# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NLightning.Wasm .NET Build & Tests (Push)
on:
  push:
    branches: [ "*" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-wasm-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build --configuration Release.Wasm
        working-directory: test/BlazorTests/NLightning.Blazor.Tests
      - name: Check Code Formatting
        run: dotnet format --verify-no-changes
        working-directory: test/BlazorTests/NLightning.Blazor.Tests
      - name: Install Dependencies
        shell: pwsh
        run: bin/Release.Wasm/net9.0/playwright.ps1 install chromium
        working-directory: test/BlazorTests/NLightning.Blazor.Tests
      - name: Test
        run: dotnet test --no-build --configuration Release.Wasm --verbosity normal --logger trx --collect:"XPlat Code Coverage"
        working-directory: test/BlazorTests/NLightning.Blazor.Tests
      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: "test/BlazorTests/NLightning.Blazor.Tests/**/*.cobertura.xml"
          targetdir: "${{ github.workspace }}"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgeneratortool"
      - name: Upload Combined Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage.Wasm
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 5
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"